---
- name: Install Apache or httpd
  hosts: dev
  become: yes
  tasks:
    - name: Install Apache on Debian
      apt:
        name: apache2
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install httpd on RedHat
      yum:
        name: httpd
        state: present
      when: ansible_os_family == 'RedHat'

